baseURL = "https://example.com/"
enableRobotsTXT = true
enableGitInfo = true

[module]
proxy = "direct"

[[module.imports]]
path = "github.com/defenseunicorns/defense-unicorns-hugo-theme"

[[module.imports]]
path = "github.com/defenseunicorns/defense-unicorns-hugo-theme/dependencies"

[languages.en]
languageName = "English"

[languages.en.params]
title = "Docs Template"
description = "Docs Template"

[params]
_merge = 'deep' # Use theme defaults
copyright = "Defense Unicorns"
github_repo = "https://github.com/defenseunicorns/doc-template-site"
github_project_repo = "https://github.com/defenseunicorns/doc-template-site"
github_subdir = "content/en"
archived_version = false
version = "v1.0.0" # x-release-please-version

# version_menu = "v1"
# url_latest_version = "https://latest-version"
# Add your release versions here that references the deployed release branch for that version.
# [[params.versions]]
# version = "v0.3 - Latest"
# url = "https://latest-version"
# [[params.versions]]
# version = "v0.2"
# url = "https://v02-version"
[params.ui]
navbar_logo = "img/doug.svg" # The product logo on the navbar

[[params.socialLinks]]
name = "GitHub"
url = "https://github.com/defenseunicorns/doc-site-template"
icon = "fa-brands fa-github"
desc = ""

### Other social links
# [[params.socialLinks]]
# name = "Community Slack"
# url = "https://communityinviter.com/apps/kubernetes/community"
# icon = "fa-brands fa-slack"
# desc = "Discussion and help from your fellow users"
# [[params.socialLinks]]
# name = "Twitter"
# url = "https://twitter.com/DefenseUnicorns"
# icon = "fa-brands fa-twitter"
# desc = "Defense Unicorns Twitter"
### Mermaid theme choices
#[params.mermaid]
# theme = "neutral" # You can override this default dark theme with other Mermaid themes
[[module.mounts]]
source = "content/en"
target = "content"

## The following merge in theme defaults from: https://github.com/defenseunicorns/defense-unicorns-hugo-theme/tree/main/config/_default
[markup]
_merge = 'shallow'

[outputs]
_merge = 'shallow'

[imaging]
_merge = 'shallow'

[taxonomies]
_merge = 'shallow'
