baseURL = "https://example.com/"
enableRobotsTXT = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[module]
proxy = "direct"

[[module.imports]]
path = "github.com/defenseunicorns/defense-unicorns-hugo-theme"

[[module.imports]]
path = "github.com/defenseunicorns/defense-unicorns-hugo-theme/dependencies"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML", "RSS", "print"]

[imaging]
resampleFilter = "catmullRom"
quality = 75
anchor = "Smart"

[languages.en]
languageName = "English"

[languages.en.params]
title = "Docs Template"
description = "Docs Template"

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"

[params]
homePage = "/docs" # If this is removed then then the site will show a landing page.
show_metalinks = false
copyright = "Defense Unicorns"
github_repo = "https://github.com/defenseunicorns/doc-template-site"
github_project_repo = "https://github.com/defenseunicorns/doc-template-site"
github_subdir = "content/en"
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
offlineSearch = true
offlineSearchSummaryLength = 70
offlineSearchMaxResults = 10
prism_syntax_highlighting = false
archived_version = false

# version = "v0.0.3"
# version_menu = "v0.3"
# url_latest_version = "https://latest-version"
# Add your release versions here that references the deployed release branch for that version.
# [[params.versions]]
# version = "v0.3 - Latest"
# url = "https://latest-version"
# [[params.versions]]
# version = "v0.2"
# url = "https://v02-version"
[params.ui]
navbar_logo = "img/doug.svg" # The product logo on the navbar
sidebar_menu_compact = true
sidebar_menu_foldable = false
sidebar_cache_limit = 10
breadcrumb_disable = false

# navbar_search = true # If true, moves the searchbar to the navbar. Not recommended for mobile!
[params.ui.readingtime]
enable = true

# [[params.socialLinks]]
# name = "Community Slack"
# url = "https://communityinviter.com/apps/kubernetes/community"
# icon = "fa-brands fa-slack"
# desc = "Discussion and help from your fellow users"
# [[params.socialLinks]]
# name = "Twitter"
# url = "https://twitter.com/DefenseUnicorns"
# icon = "fa-brands fa-twitter"
# desc = "Defense Unicorns Twitter"
[[params.socialLinks]]
name = "GitHub"
url = "https://github.com/defenseunicorns/doc-site-template"
icon = "fa-brands fa-github"
desc = ""

[params.plantuml]
enable = true
theme = "default"
svg_image_url = "https://www.plantuml.com/plantuml/svg/"
svg = false

[params.print]
disable_toc = false

[params.markmap]
enable = true

[params.mermaid]
theme = "default"

[params.mermaid.flowchart]
diagramPadding = 20

[params.drawio]
enable = true

[taxonomies]
tag = "tags"
category = "categories"

[[module.mounts]]
source = "content/en"
target = "content"
