# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
  command = "npm ci && hugo --gc --minify"
  publish = "public"

  [build.environment]
    GO_VERSION   = "1.22.3"
    HUGO_VERSION = "0.126.3"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
